### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#1]

**Comment by meschw04** [comment]
Testing should demonstrate abilities three major data modalities:
Tabular data
Image data
Spectral data

Testing should also demonstrate abilities of three major modeling modalities:
Supervised Learning (KRR, GPs, &c)
Unsupervised Learning (Clustering, PCA, &c)
Deep Learning (TF/keras and Pytorch, various architectures)

**Comment by blaiszik** [comment]
I'm not sure testing needs to include the modeling aspects, but we could definitely include that in the examples.
