### ISSUE TITLE
Some thoughts on using Foundry in geosciences (xarray, netcdf, zarr, etc.) 

### ISSUE THREAD

**Issue by rabernat** [MLMI2-CSSI/foundry#172]
This issue is a follow up to the great discussion we had at the [Pangeo + Globus Labs meeting](https://discourse.pangeo.io/t/pangeo-globus-labs-meeting-and-discussion/2308) earlier this week.

Foundry seems like a great project that would fill and important niche in the geosciences: allowing scientists to publish simulation data from their globus-connected HPC systems to share with the broader world. As I understand it, Foundry is currently focused exclusively on supervised machine-learning datasets that fit into the `intput` / `target` paradigm. This certainly captures some of the needs in geosciences, but not all of them. Sometimes people just want to publish a dataset for general consumption, not specifically for ML. So my first question is _whether there is scope in the project for more generic dataset publishing via globus?_ If not, can you point me towards any other projects in that space? 

Even if the answer is no, I think we will still want to use Foundry to publish ML-focused data in the geosciences.

Leaving that question aside for now, here are some random thoughts on what might make Foundry useful / appealing for geoscience / ocean / weather / climate / etc. users.

---

### NetCDF is our data model

Foundry currently supports two data types: tablular data and hierarchical data. In geosciences, we tend to use a similar schema to distinguish between data types. However, we tend to say tabular data vs. array data. And in the geosciences, 99% of array data is encoded in the [NetCDF data model](https://docs.unidata.ucar.edu/netcdf-c/current/netcdf_data_model.htm). And probably 80% uses [CF Conventions](https://cfconventions.org/).

When data follow these conventions, the dataset metadata already contain fields like `standard_name`, `description`, `units`, etc. etc. within the data files themselves (i.e. self-describing). Consequentially, some  of the [metadata that Foundry requires for describing datasets](https://ai-materials-and-chemistry.gitbook.io/foundry/publishing/publishing-datasets#describing-datasets) may be redundant. So a major design question for incorporating NetCDF-type data into Foundry would be _how to harmonize Foundry's metadata requirements with the metadata standards commonly used in geosciences via NetCDF / CF conventions._ Perhaps some of the Foundry metadata could be automatically discovered by examining the data.

### Xarray is our python API

Just like Pandas provides data structures and a computational API that matches the tabular data model, [xarray](https://docs.xarray.dev/en/stable/) provides data structures and a computational API that matches the NetCDF data model. So just like Foundry maps tabular data to be opened in Pandas, we would want to _map NetCDF-style data to be opened in Xarray_.

Xarray also serves as swiss-army knife of file formats. Similarly to Pandas, It can read [dozens of different data formats](https://docs.xarray.dev/en/stable/user-guide/io.html) and load them all into the same data model. This is a huge cognitive boost for scientists, who can then easily write analysis code that interoperates with any of these formats.

### Our files are NetCDF, [Cloud Optimized] GeoTIFF or Zarr

For the most part, I imagine geoscientists wanting to share array data via Foundry will be using one of three formats.
- **NetCDF**, often with hundreds / thousands of files in folder, arranged sequentially along some dimension such as time. (Note that Xarray [can open these collections](https://docs.xarray.dev/en/stable/user-guide/io.html#reading-multi-file-datasets) as single Dataset object, leveraging Dask. I see this feature has come up elsewhere in Foundry: #52. Under the hood, NetCDF4 files are HDF5, but as a rule we almost never open them directly with h5py, preferring to use the NetCDF model instead.
- **Cloud Optimized GeoTIFF** (or [COG](https://www.cogeo.org/)) is the predominant format for _geospatial imagery data_. Each file holds a single multiscale image. The files are often catalogued using [Spatio-temporal asset catalog](https://stacspec.org/). The [Radiant Earth MLHub](https://mlhub.earth/) holds lots of remote sensing ML training datasets and shares similar aims to Foundry, so that might be a worthwhile project to investigate.
- **[Zarr](https://zarr.readthedocs.io/)** - Zarr is a hierarchical format similar to HDF5. However, rather than storing everything in a single file, Zarr explodes the data into many individual files / objects, including separate json metadata. This has [advantages and disadvantages](https://par.nsf.gov/servlets/purl/10177969) depending on your context. (HPC filesystems tend not to love lots of small files; cloud object stores work great with it). One clear advantage is that it is trivial to append to these datasets along any dimensions. So where we might have 1000 individual netCDF files, we would only have one single Zarr store. When sharing Zarr data via Foundry, we would probably just share a single Zarr group (potentially comprised of thousands of individual files, which have no meaning outside the context of the Zarr group / array). Like with NetCDF, there is a question of redundancy between the metadata stored in Zarr itself vs. input to Foundry.

---

If you're interested in moving this forward, we would be happy to serve as guinea pigs 🐹 in exploring Foundry for geosciences. We have many datasets sitting on globus-connected systems that we would like to publish.

cc @mgrover1, @scollis, @cisaacstern, @jbusecke,

**Comment by rabernat** [comment]
See https://github.com/pangeo-forge/pangeo-forge-recipes/issues/222#issuecomment-1080830165 for a success story of loading Zarr data via globus HTTPS endpoints! 🚀

**Comment by ascourtas** [comment]
Hi @rabernat thank you for this thoughtful deep dive on how we can integrate! Apologies for the delay here, I had missed this Issue (thank you to Ben for pointing it out today). To answer your first question, yes I think there is definitely both scope and desire to make Foundry capabilities generalizable across domains! That's our ultimate goal. 

You raise excellent questions about the "how", which I need to discuss with the team, but it definitely sounds like we should chat to discuss priorities, goals, timelines, etc.
