### ISSUE TITLE
fix Apple M1 bug with keras

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#184]
Currently blocking any TF/Keras related development or use on M1 machines.

Info here: https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook

https://stackoverflow.com/questions/65242614/why-does-loading-tensorflow-on-mac-lead-to-process-finished-with-exit-code-132

Seems TF 2.6 is now supported via its PluggableDevice interface?
https://makeoptim.com/en/deep-learning/tensorflow-metal

alternatively, here was the custom macOS solution (now archived/obsolete): https://github.com/apple/tensorflow_macos

https://developer.apple.com/metal/tensorflow-plugin/

related issue with conda, TF, and M1 https://stackoverflow.com/questions/67395283/switch-between-anaconda-and-miniconda-miniforge

**Comment by blaiszik** [comment]
Is this still a problem?

**Comment by ascourtas** [comment]
@blaiszik sorry I missed this, I just checked and it is still an issue with Tensorflow/Keras
