### ISSUE TITLE
Set up a monitor to check CI status of core services

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#186]
For services like DLHub, funcx, Xtract, etc we want to make sure we have testing (ideally daily) to know when something is down. Otherwise we go on a goose hunt for Foundry.

From Ben G.: This seems like a powerful component to tie everything together: https://reportportal.io/features

**Comment by blaiszik** [comment]
XTract has been decommissioned.

**Comment by blaiszik** [comment]
Closing since DLHub testing is done daily via GitHub Actions
