### ISSUE TITLE
Set up Sphinx Autodocs

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#189]
Set up [Sphinx](https://www.sphinx-doc.org/en/master/index.html) with our GitBook docs. Publish from the `docs` GitBook branch.

**Comment by blue442** [comment]
Just for clarification, is the intent here to publish the .md content from the docs folder via sphinx, or are we looking to document the foundry code itself? Also are we looking to deploy it via github pages, or readthedocs, or something else?

**Comment by blaiszik** [comment]
This is mostly completed minus a permissions issue with the bot pushing back to `main`. Should we unprotect the branch, or are there other ways around this?



![Image](https://github.com/MLMI2-CSSI/foundry/assets/4753182/e5dba8e0-40de-46dc-b682-5518efc99335)

**Comment by blaiszik** [comment]
I've verified that this works without branch protection. We can create a new issue to deal with the auth aspects if needed. Do we suspect we actually need branch protection? We already limit who can push via access control.
