### ISSUE TITLE
update tests for Foundry `publish()` to auto-clean

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#190]
When testing the Foundry publish() method, test-packages get published to the destination endpoint (currently on UIUC). Right now we are manually clearing them, but we should programmatically clean them up instead, at the end of our test suite.

Add the necessary clean up methods (that require using the Globus SDK) to the end of the test suite

checkin with Ben about the Globus SDK methods to use

Also want to clean up model publication detritus, if possible (check in with Logan)

(NOTE: also don't have a method for this in MDF CC, should probably add one)

**Comment by kjschmidt913** [comment]
Dependent on issue #23 being completed first. Would suggest also adding the functionality in issue [#187](https://github.com/MLMI2-CSSI/foundry/issues/187) before starting this issue so you can update the tests for that if necessary
