### ISSUE TITLE
add tests for model running 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#195]
We need to add tests to `test_foundry_gha.py` for running DLHub models -- especially those with different funcx endpoints IDs (meaning the containers run on a server other than the default, which has been UC River) and older models published with varying versions of DLHub SDK and Globus SDK (this is particularly important given the code-breaking changes from Globus SDK 2 to 3). 

Here are the two stubbed out tests in question (with models provided to test servables published with different versions of DLHub and Globus SDK 3, to ensure that they all still work when running using current DLHub, Globus SDK, and funcX versions). `test_model_run_endpoint()` will test running a model when a different funcx endpoint is specified. 

Please add the assertions needed to make these tests function properly. Additionally, we should specify exactly which DLHub SDK versions were used for each model (which can be found at dlhub.org by searching by model name). 

```
def test_model_run():
    f = Foundry()
    # test old model published with old DLHub, Globus SDK 2
    res = f.run('zhuozhao_uchicago/Noop', [1, 2, 3, 2, 2, 3])

    # test model published with newer DLHub, Globus SDK 2
    res = f.run("aristana_uchicago/noop_v14", {"data": True}, debug=True)

    # test model published with newest DLHub, Globus SDK 3
    res = f.run("aristana_uchicago/noop_dlhub_v4", {"data": True}, debug=True)

    res = f.run("aristana_uchicago/noop_dlhub_v4", True, debug=True)

    res = f.run("aristana_uchicago/noop_dlhub_v4", {"data": True})


def test_model_run_endpoint():
    f = Foundry()

    # test data
    X_test = np.zeros((11, 11))
    x_cen, y_cen = 6.0, 5.0   
    sig_x, sig_y = 0.6, 1.5
    for x in range(11):
        for y in range(11):
            X_test[y][x] = 1000*(np.exp(-(x-x_cen)*(x-x_cen)/2*sig_x -(y-y_cen)*(y-y_cen)/2*sig_y))
        
    # the input needs to be normalize to 0-1, e.g., rescale using min-max norm
    X_test = (X_test - X_test.min()) / (X_test.max() - X_test.min())

   # inputs
    inputs = X_test[np.newaxis, np.newaxis].astype('float32')

    # run the BraggNN model trained using plain PyTorch 
    res = f.run("kj.schmidt913_gmail/BraggNN_PT", inputs, funcx_endpoint='7d7d5826-6167-4d6e-a591-b57628d60588')

```

**Comment by WardLT** [comment]
Do we need to solve this in Foundry? I'm not sold on having a second interface to DLHub that's actually part of the Foundry client.

**Comment by ascourtas** [comment]
Agreed, these slightly more comprehensive tests should probably just be a part of the DLHub test suite? How do you feel about that Logan
