### ISSUE TITLE
assess Foundry dataset documentation

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#196]
Read through the Foundry Dataset documentation for understanding in GitBook. Add comments for areas that could use clarification or improvement.

**Comment by Aadit-Ambadkar** [comment]
Issue #198

**Comment by Aadit-Ambadkar** [comment]
I think that the Foundry Datasets and the Publishing Datasets can be combined.

**Comment by kjschmidt913** [comment]
@Aadit-Ambadkar The thought being keeping those separate is that there are 2 kinds of users for datasets: users that would like to publish a dataset, and users that would like to load a dataset.

I see you've created issue 198- could you assign that to yourself and update the progress of that?

**Comment by Aadit-Ambadkar** [comment]
Looks like that's done. I think that was the only issue I had with this.
