### ISSUE TITLE
Consider other data types we need to support

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#20]

**Comment by meschw04** [comment]
One good way for us to decide which other data types to support: we ought to go through MDF datasets and see which would be best fit to foundry (and ultimately add them). Depending on the data types for the datasets we would like to add, we can build functionality for these data types in preparation for this.

**Comment by kjschmidt913** [comment]
Ryan recently suggested we should support pickle files

**Comment by kjschmidt913** [comment]
Please add any other data types you think would be beneficial to support in the comments!
