### ISSUE TITLE
Actually fail when flake8 finds problems

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#208]
The CI testing only issues warnings and not errors when Flake8 finds problems. I'm not sure if you intended this, as it's the default for GHA's python CI template.

https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/.github/workflows/testing-work.yml#L47

**Comment by Aadit-Ambadkar** [comment]
i think can be close right now?

**Comment by WardLT** [comment]
It appears so. Thanks, @Aadit-Ambadkar !
