### ISSUE TITLE
update `f.publish()` and examples to handle `short_name` appropriately

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#209]
Currently, a user can specify the `short_name` in both the dataset metadata at publication time, and pass it in as an argument. 

Only the argument is used to form the `source_id` for the dataset, but that is not communicated to the user and is confusing. 

- [ ] check to see if having `short_name` in the metadata serves any purpose at all. If not, take it out of all notebook and documentation examples
- [ ] if there is a purpose for having `short_name` in the metadata, make sure it is used as though the user passed in the argument
- [ ] make it clear to the user what the use case is for specifying `short_name`

**Comment by kjschmidt913** [comment]
This should be addressed in the refactor
