### ISSUE TITLE
Update Foundry Data Publishing Notebook

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#210]
[The Foundry Data Publishing notebook](https://github.com/MLMI2-CSSI/foundry/blob/main/examples/publishing-guides/dataset_publishing.ipynb) is a guide that walks users through how to publish their data on Foundry. Go through the publishing process and update the notebook's text and screenshots as needed. 

We noticed recently that for providing the data source, the way to get the shareable link has changed. You need to select the download the file directly link. This may involve adding a new screenshot for this section.

**Comment by kjschmidt913** [comment]
Include HTTPS upload after it's merged in

**Comment by kjschmidt913** [comment]
Alright so the screenshots are actually still accurate. So update this when HTTPS is merged in

**Comment by ascourtas** [comment]
briefly blocked on Foundry release -- should be resolved shortly

**Comment by ascourtas** [comment]
currently blocked on minor GHA issue -- should be resolved with updating scopes

**Comment by ascourtas** [comment]
Reviewed and merged!
