### ISSUE TITLE
handle multiple matches in `load()`

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#211]
In `Foundry.load()`, currently we assume that Forge will only return one matching dataset/model in Foundry (or at least, we only take the first one returned).

Amend this to handle the case where multiple matches may be returned.

the ideal behavior here would be to throw a warning to the user if multiple datasets are returned

See TODO in below code snippet

     def load(self, name, version="1.1", provider="MDF", download=True, globus=True, verbose=False, **kwargs,):
        """Load the metadata for a Foundry dataset into the client
        Args:
            name (str): Name of the foundry dataset
            download (bool): If True, download the data associated with the package (default is True)

        Keyword Args:
            interval (int): How often to poll Globus to check if transfers are complete

        Returns
        -------
            self
        """
        res = []
        # MDF specific logic
        # Handle DOI inputs
        if name.startswith("10.") and provider == "MDF":
            print("Loading by DOI")
            res = (
                self.forge_client.match_dois(name)
                .match_resource_types("dataset")
                .match_field("mdf.organizations", "foundry")
                .search()
            )

        # Handle MDF source_ids
        else:
            print("Loading by source_id")
            res = (
                self.forge_client.match_field("mdf.organizations", "foundry")
                .match_resource_types("dataset")
                .match_field("mdf.source_id", name)
                .search()
            )

        if not res:
            return self
        else:
            # res is list of all matches in Forge
            # TODO: handle if there are multiple matches
            res = res[0]

            # map result to FoundryMetadata Pydantic structure (see models.py)
            res["dataset"] = res["projects"]["foundry"]
            res["dataset"]["type"] = res["dataset"]["package_type"]
            del res["projects"]["foundry"]

            # TODO: reassign values to self in a safer way
            self = Foundry(**res)

        if download is True:  # Add check for package existence
            self.download(
                interval=kwargs.get("interval", 10), globus=globus, verbose=verbose
            )

        return self

**Comment by Aadit-Ambadkar** [comment]
This was done 😳
