### ISSUE TITLE
Update `collect_dataframes` in Foundry SDK

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#214]
The collect_dataframes method is meant to concatenate dataframes of the same shape across multiple datasets. It is currently out of sync with the other loading methods.

https://github.com/MLMI2-CSSI/foundry/blob/515ec7920e43c5e99c356a183e1ef00fa237214e/foundry/foundry.py#L160

`collect_dataframes` should only work on `tabular` datasets. If non-tabular data are included, the function should return an error

It would also be nice if this was robust enough to allow for combination of dataframes that were not exactly the same shape. Though this requires some thought about None valued entries

**Comment by blaiszik** [comment]
collect_dataframes has been removed. May be useful to revisit in the future.
