### ISSUE TITLE
Add function to return citations for current data cache (bibTex or string)

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#215]
We should capture citation information for all Foundry data packages, and make it easy to return the citations used for a given data package

Add this to MDF instead, because it will be generally useful

Add "preferred_citation" to MDF metadata

**Comment by blaiszik** [comment]
#274 implements direct dataset citation

We should open a new issue for paper citations

**Comment by ascourtas** [comment]
@blaiszik it sounds like we should close this, is that right?
