### ISSUE TITLE
Testing should use pytest's tmpdir rather than manage cleaning files manually

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#219]
We have a lot of unnecessary complexity in our tests, such as the `_delete_test_data` function. We can replace that with pytest's `tmpdir` fixture or the [teardown logic](https://docs.pytest.org/en/latest/how-to/fixtures.html#teardown-cleanup-aka-fixture-finalization) that also relies on fixtures.

**Comment by kjschmidt913** [comment]
our testing suite is getting overhauled in this refactor, so closing this issue for now
