### ISSUE TITLE
Pytest and Travis deploy

### ISSUE THREAD

**Issue by meschw04** [MLMI2-CSSI/foundry#22]
The current state of `tests/test_foundry.py` is just to pass without flagging. There are several areas that need to be fixed here.
First, we need to make sure that tests actually pass when running `f=Foundry()`, mostly making sure that this part passes Globus Auth (recall problems around `.gloubs-native-apps.cfg` and `travis.tar.enc`). Use the tests from MDF forge as a template for this.
Second, place a `test.json` (or similar) on the endpoint used for foundry examples. Use asserts to make sure foundry can get to the endpoint. Once again, refer to MDF forge tests.
Third, make sure that Foundry can run a simple model (say, for eg., Ryan Chard's StringLength function) and return a correct result for some set input.

**Comment by blaiszik** [comment]
Skip Travis and implement with GitHub Actions
