### ISSUE TITLE
Role of the `Foundry` object is too flexible, separate query and result

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#220]
**Is your feature request related to a problem? Please describe.**
The `Foundry` object holds too many roles, which is likely to lead to some development issues. For example, it is both the object for performing queries and the result object:

```python
from foundry import Foundry

f = Foundry()
f.load('10.18126/rp13-3k3h')  # Foundry acting as a query client
res = f.load_data()  # Foundry acting as a result

df = res['data']
```
The use of the Foundry object in this way leads to a bit of complexity:

1) _User complexity_: Foundry holds a lot of statem, which means knowing what commands were executed previously (e.g., `f.load`) is required to know what will happen when you call other functions (`f.load_data`). Users also have to skim through many irrelevant functions to match what they need.
2) _Development complexity_: Every new feature in Foundry is getting added to the Foundry class, which is going to lead to that class drastically expanding in size and difficulty of debugging. All the above problems with users knowing how the use the object will also propagate to developers trying to add new functionality.

**Describe the solution you'd like**
Have `Foundry` return result objects specific to certain types of data. E.g., `load` should return a `FoundryDataset` type if the query matches a dataset. Any functionality related to manipulating that dataset (e.g., downloading it, converting it into different types) will be placed inside of the result class.

**Describe alternatives you've considered**
- Keeping things as they are and documenting the class very extensively. 

**Additional context**
- Forge probably still has this behavior too.

**Comment by kjschmidt913** [comment]
This is addressed in the Foundry refactor work
