### ISSUE TITLE
Printing to screen for non-critical errors is unnecessary 

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#221]
There are a few instances where we print directly to stdout from code. That's rarely used in Python scripts as it is difficult to control whether `print` goes to screen or not. People are stuck with it unless they mess with `sys.stdout` (not recommended). 

Consider switching these to logging statements instead.

Example: https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/foundry/foundry.py#L764

**Comment by blaiszik** [comment]
Is this completed?

**Comment by WardLT** [comment]
Yes, I don't see any more print statements.
