### ISSUE TITLE
Switch downloading from joblib to ThreadPoolExecutor

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#223]
Joblib is a great library, but we don't need it for downloading files in parallel. Consider using [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example) instead, as this will consume fewer resources (no need to create a separate Python process) and allow us to drop another requirement from the library.

Core line: https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/foundry/foundry.py#L692

**Comment by blaiszik** [comment]
Closed with #273
