### ISSUE TITLE
Data importing logic is overly complicated

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#224]
We use nested try-except blocks to attempt to determine a data type currently, and there are a few alternatives to this which should be considered:

1. _Provide the list of possible functions as a list._ You can still use try/except to evaluate each one, but it will avoid having to nest them inside each other. Just break the loop if one passes and continue if not.
1. _Don't rely on automatically guessing each time you load the dataset._ Get the format once on publication then read it from the Foundry record. We had code to do this back in a super-early version of DLHub SDK: https://github.com/DLHub-Argonne/dlhub_sdk/blob/v0.4.0/dlhub_sdk/models/datasets.py#L70

https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/foundry/foundry.py#L759

**Comment by blaiszik** [comment]
#271 addresses Part 1.
