### ISSUE TITLE
update documentation for xlsx files

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#226]
Once issue #225 has been completed, update the Foundry documentation. We thought we supported xlsx files so there are already a few things in the docs about this datatype. Please update and add what the user needs to know to use this datatype successfully.

**Comment by blaiszik** [comment]
This functionality is included now. For now, only pandas default params are working with read_excel

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html
