### ISSUE TITLE
Add ability to publish models through Foundry

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#23]
Via DLHub, enable model publication as a pass-through from this client

**Comment by kjschmidt913** [comment]
Currently, users publish models through DLHub via `dl.publish()`. Once published through DLHub, users can run their models with Foundry via `f.run()`. We would like to create a Foundry wrapper for the DLHub publishing functionality so users can publish and run their models all with Foundry.

**Comment by isaac-darling** [comment]
Slack discussions led to decisions regarding how to proceed on this general functionality, which in turn resulted in some heterogeneous development across components in the DLHub SDK. To be elaborated upon.
