### ISSUE TITLE
Make code style problems raise errors in GitHub Actions 

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#230]
We use only raise warnings for style problems, which is GitHub's default flake8 behavior. 

Changing to raise errors means these style problems won't get ignored. 

https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/.github/workflows/testing-work.yml#L47

**Comment by blaiszik** [comment]
Is this completed?

**Comment by WardLT** [comment]
Yes, it was also a duplicate of #208 (whoops!)
