### ISSUE TITLE
Remove commented code

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#234]
Commented-out code tends to become broken over time, so actually using it again is never as simple as just commenting it back in. 

My suggestion is to delete the code and publish a release when we delete it. A tag makes it so you can easily find when the code was removed, inform users that the functionality is gone (even if temporarily), and simplify checking out a version of code where the deprecated stuff "should" work. 

https://github.com/MLMI2-CSSI/foundry/blob/7b9427df2b12ea4f2880e5e550d5880cde37768f/foundry/foundry.py#L16

**Comment by blaiszik** [comment]
Closed with #272
