### ISSUE TITLE
Is an account required for a user to download a dataset?

### ISSUE THREAD

**Issue by sgbaird** [MLMI2-CSSI/foundry#239]
In contrast to e.g. FigShare where you can use a no-authorization direct download link. [The docs](https://ai-materials-and-chemistry.gitbook.io/foundry/#globus) make it seem like Globus authentication is required for *both* data download and/or publishing, but I think it could be made more explicit in the intro if that's the case.

**Comment by blaiszik** [comment]
Thanks Sterling, we will clarify this. For MDF Open (95% of our data) and Foundry, the data are available for anonymous download.
