### ISSUE TITLE
Are DOIs assigned via Foundry (or is this in the near-term plans)?

### ISSUE THREAD

**Issue by sgbaird** [MLMI2-CSSI/foundry#240]
I wasn't totally clear on whether [the DOI mentioned](https://ai-materials-and-chemistry.gitbook.io/foundry/examples#loading-datasets) is a DOI to an external article/dataset/etc. or if it's one assigned by Foundry upon publishing. Wondering if I should upload a dataset to FigShare or similar first for a DOI and then upload it to Foundry afterward.

Excited to try Foundry out at some point.

**Comment by blaiszik** [comment]
Yes, Foundry and MDF both support DOI minting by default. Let me know if we can help you through the process.
