### ISSUE TITLE
get codebase inline with PEP8 standards per flake8

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#245]
We added flake8 linting and wow do we have a lot of small things that need fixing!

Get the repo inline with Pythonic standards using the flake8 output as a guide 

https://github.com/MLMI2-CSSI/foundry/runs/7750729434?check_suite_focus=true

**Comment by blaiszik** [comment]
Is this completed?

**Comment by blaiszik** [comment]
Repo passes flake8. Closing this issue
