### ISSUE TITLE
create a metadata formatter form that outputs Foundry metadata

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#264]
ideally, the user could enter their metadata info into an online form that generates the metadata JSON

**Comment by WardLT** [comment]
A set of Pydantic classes (as in DLHub) would also be helpful to keep users from writing straight JSON in the Python interface

**Comment by WardLT** [comment]
Perhaps even make it auto-populate metadata fields (e.g., names of keys, how to read a tabular file) after reading it.

**Comment by blaiszik** [comment]
Form hosted somewhere on foundry-ml.org

**Comment by kjschmidt913** [comment]
We're redoing the metadata structure in the refactor to make it easier for users to fill out correctly. Closing this issue for now. We can reopen it if we decide it's still relevant post refactor
