### ISSUE TITLE
ChiMaD OutReach

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#268]
- Look into social media organization/shared docs
- Write out content for tweets and linkedin posts

10/3
found this template from hootsuite: https://docs.google.com/spreadsheets/d/1GADxvHGQIsDDDugJ5ij8L43JYlXMcxSX-h5PA0ZyQnc/edit#gid=1560739129

I will make a copy and start filling it in

Find a composer for threads

10/14
link to og chimad doc: https://docs.google.com/document/d/17aspoCMOWQVhK2Xq-MLhW6xP3IiWwT9svJ7mEkCclkw/edit#heading=h.qeig83xb8lnq

10/21

Social doc is mostly filled in. Things that need attention:

- Filling in datasets that we want to highlight (we need 5)
- Filling in CHiMaD presentations in the past that were great
- The final week of MDM has 2 blank days
- Come up with Shout Out list
- Need 2 tweets about about EFRCs and AI Institutes
- Thread for day one needs to be filled in
- Write formal Foundry launch thread

**Comment by kjschmidt913** [comment]
@blaiszik Do you have ideas for anything that still needs to be filled in from the list above? Like datasets to highlight, people for shout outs, old CHiMaD presentations, etc.

I can write the formal foundry launch but the rest I wondered if you had thoughts on before i attempted
