### ISSUE TITLE
Parallelize HTTPS upload 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#279]
_As a Dataset Publisher, I want to be able to upload my data quickly and easily_

# Assumptions

1. HTTPS upload functionality works properly already
2. Parallelizing does not impact the written directory structure
3. Parallelizing does not impact the publisher's reception of error messages

# Acceptance Criteria
1. Given I have a dataset to upload, I can do so in rapid time (ideally less than 1 min), even for datasets that are many GB in size 
2. Assumptions 2 and 3 are still met 

# Tasks

- [ ] Parallelize existing HTTPS upload code in `publish()`

**Comment by kjschmidt913** [comment]
since https upload will be tackled during publishing refactor, closing this
