### ISSUE TITLE
Add a "test" mode for validating metadata without publishing

### ISSUE THREAD

**Issue by WardLT** [MLMI2-CSSI/foundry#282]
**Is your feature request related to a problem? Please describe.**
I am preparing a notebook and don't want to publish now, but I won't know if I'm close to correct until we try to publish.

**Describe the solution you'd like**
A "dry run" function on publication that tests against the schema and ensures the data are accessible, but does not create a record in Foundry.

**Describe alternatives you've considered**
Publish then ask Foundry to delete my incomplete dataset.

**Additional context**

**Comment by ascourtas** [comment]
This was handled in #377 for #218  -- the user can now run `f.validate_metadata()`

Closing until further notice
