### ISSUE TITLE
Validate metadata can successfully load data before publishing

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#286]

**Comment by blaiszik** [comment]
The metadata should be able to be used to load the data

Building a dry run unction to test this locally would be helpful to allowing users to understand if their metadata was valid before failing at the MDF curation step (which can take a while)


You should be able to **data argument in the constructor with the provided metadata in a new client
```
metadata = {...}

f_local = Foundry(**metadata)

f_local.load() //within the directory you are publishing from. 

# Pass back errors to user 

```

**We need to specify the data directory since the default is at ./data from where the call is made**

**Comment by ascourtas** [comment]
Does this dupe #282 ?

**Comment by ascourtas** [comment]
This issue is moot given the solution in #377 for #218 

Closing until further notice
