### ISSUE TITLE
Write Medium Articles that feature Foundry

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#288]
Write Medium articles that feature or highlight Foundry.

This could be a tutorial, a exploration of Foundry's features, or a story about the problem Foundry solves and how it solves it.

**Comment by blaiszik** [comment]
Minor edits have been added inline. Biggest change is the need to update Foundry to Foundry-ML.


- https://medium.com/@kj_schmidt/access-large-scientific-datasets-the-easy-way-foundry-d89a126d9f50
- https://medium.com/@kj_schmidt/the-future-of-sharing-large-scientific-datasets-is-here-97d575de58ec

**Comment by kjschmidt913** [comment]
Updated and published!

**Comment by ascourtas** [comment]
closing this unless someone tells me otherwise
