### ISSUE TITLE
Update media with new logo

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#289]
Foundry is rebranding to Foundry-ML. Update logo on:

- Medium Articles
- Website
- Presentation for ESIP

Anywhere else?

**Comment by blaiszik** [comment]
We should update the GitHub repo too.

https://github.com/MLMI2-CSSI/foundry

**Comment by ascourtas** [comment]
since this is set to done, I'm closing this unless someone tells me otherwise
