### ISSUE TITLE
MDF Interface Updates

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#293]
Break this out into smaller stories, when the time comes for the UI updates:

- [ ] - [ ] form fits on one screen
- [ ] clean up ordering of tags and dates in Search page
- [ ] move "latest news" to side bar?
- [ ] Globus interface is a bit funky for datasets
- [ ] Need a direct download button
- [ ] Featured datasets
- [ ] When you're on the publishing route (/add) the navbar doesn't work
- [ ] Links to add
     - paper
     - Foundry dataset
     - Garden
     - Code?
- [ ] better whitespace and div balance
- [ ] More color on the front end
- [ ] Need a group check on the /add dataset page. Otherwise error happens too late in the process
- [ ] stats on views/downloads?
- [ ] Foundry datasets need more info
- [ ] on dataset page, button: specify that this is with globus, not a straight up download link
- [ ] revamp Dataset Status page -- fugly

**Comment by ascourtas** [comment]
idk if this was already captured in the "content" story, but a couple of things from the Future of MDF and Foundry Miro board that I didnt see here were:
- Call to action in the search results is "Globus", which is not a verb -- update
- Have landing page include banner about searching before it gets into publish instructions

**Comment by kjschmidt913** [comment]
Oh yeah, that's captured on the draft: Website Update: Other MDF pages

I made it in the board and can't convert it into an MDF issue there
