### ISSUE TITLE
Publish Form Markdown Preview

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#294]
[publish page] Markdown rendering in the same desc box. Make a preview tab so users don't have to scroll down to see. Use Quill or another standard editor

**Comment by blaiszik** [comment]
Completed as part of the website redesign. Will deploy when the redesign is deployed. 



![Image](https://user-images.githubusercontent.com/4753182/218855696-0a4429fa-908b-49b2-90a8-471a5f7a47cd.png)

**Comment by ascourtas** [comment]
I see this is Done, closing unless told otherwise

**Comment by ascourtas** [comment]
my mistake, looks like it was actually In Review? reopening

**Comment by ascourtas** [comment]
needs to be deployed one KJs changes are in
