### ISSUE TITLE
Create MDF dev environment + documentation

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#298]
Create documentation for MDF dev environment so anyone can get set up locally with MDF

**Comment by blaiszik** [comment]
Web (w/ instructions): https://github.com/materials-data-facility/web
Search (w/ instructions): https://github.com/globusonline/django-alcf-data-portal
Search templates are here: https://github.com/globusonline/django-alcf-data-portal/tree/main/alcf_data_portal/templates/mdf

**Comment by ascourtas** [comment]
this is moved to Done, closing unless told otherwise
