### ISSUE TITLE
More Descriptive Error Messages

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#305]
After the container service is integrated, check if error messages are helpful. We need errors to be descriptive so the user can fix the problem

**Comment by ascourtas** [comment]
Dependent on https://github.com/DLHub-Argonne/dlhub_sdk/issues/176

**Comment by ascourtas** [comment]
Container service is integrated; users receive descriptive descriptive error messages when there's a model running failure; users can use the funcx client to view more error information, but we need to add documentation about this
