### ISSUE TITLE
Improve MDF dataset versioning 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#308]
**Is your feature request related to a problem? Please describe.**
Users have expressed the desire for improved versioning for datasets. 

**Describe the solution you'd like**
Dataset versioning should be intuitive, clear, and simple. It should be easy to track/view the posterity of a dataset, ie all past versions. A user should be able to easily invoke a particular version. Additionally, they should know which version is being pulled down (ie original vs latest) when they are loading a dataset's default version.

Exact implementation requires some research. 

**Describe alternatives you've considered**

**Additional context**
The versioning in MLFlow seems to be solid (as explored in Garden dev). Perhaps something like that? Exploring how dataset versioning is handled in something like PyTorch Datasets or Zenodo or Figshare would also be quite helpful.

**Comment by kjschmidt913** [comment]
This should be moved to MDF repo
