### ISSUE TITLE
Add tutorial on MDF Dataset page on how to access data 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#309]
**Is your feature request related to a problem? Please describe.**
It could be made clearer to the User how to access data via Globus on the MDF Dataset webpage.

**Describe the solution you'd like**
Adding a lil tutorial would help! 

**Describe alternatives you've considered**

**Additional context**

**Comment by kjschmidt913** [comment]
Also add to how to page

**Comment by ascourtas** [comment]
Part of Summer Student Redesign
