### ISSUE TITLE
globus: seems to be hard requirement

### ISSUE THREAD

**Issue by vsoch** [MLMI2-CSSI/foundry#321]
I was hoping to run some examples in an operator I'm working on, but it would be hard to create a Globus endpoint there. Is there any use case for foundry that does not require globus?

**Comment by vsoch** [comment]
Update from testing last night: I set globus to false, but it still is trying to authenticate:

![image](https://user-images.githubusercontent.com/814322/228625373-2bbcaa54-fe4d-4182-bddf-13e813ef2f5e.png)

the reason is because the Foundry() init command is doing it (not the login that takes the argument):

![image](https://user-images.githubusercontent.com/814322/228625466-b4239835-9a2b-48c9-9272-f3f7ae88b23f.png)

**Comment by WardLT** [comment]
You won't need a Globus endpoint to get data but do need to login in before using Foundry. That login is for accessing the search index and authentication procedures for HTTPS downloads of data.

@blaiszik , should we put anonymous login on Foundry?

**Comment by vsoch** [comment]
@WardLT I'm hoping there might be an option for anonymous - if we are to run this in a completely headless setting it will likely not work without that!

**Comment by WardLT** [comment]
Headless can work, you'll just have to login once from a terminal to get credentials then use the same user account or copy them to your user's home directory. Are either of those an option?

**Comment by vsoch** [comment]
No, this is running in a Kubernetes operator, so we don't have a concept of login or a user terminal.

**Comment by vsoch** [comment]
Can we use this function instead? https://github.com/materials-data-facility/toolbox/blob/e0e178ef2433811a25db76bb711c40b2552e836e/mdf_toolbox/auth.py#L37-L63

The question is probably does the anonymous client have enough permissions to download a dataset.

**Comment by vsoch** [comment]
I can try that! Is there documentation for how to generate this config?

**Comment by WardLT** [comment]
No, but you should get the "*.cfg" file after logging in the first time on your local system. i.e., `from foundry import Foundry; f = Foundry()`. That file will appear when you're done.

**Comment by vsoch** [comment]
okay - done testing! I was able to just load the datasets and then run the workflows, and it didn't matter if I ran them manually on a node or submit to flux - most of these ML frameworks don't have any kind of native support for Flux (e.g., MPI would be able to map to all the worker nodes) so we can't take advantage of the architecture. But with Foundry the focus is on retrieving the data, and I think the setup (for reproducible datasets) is quite nice. We could require generating the token beforehand, and providing it as an environment variable that gets piped into a file on the nodes. 

https://github.com/flux-framework/flux-operator/tree/add/foundry/examples/machine-learning/foundry 

I guess Foundry is mainly scoped to the dataset sharing bit, and less the running of workflows that use it? That would be where my point of interest is next, although this is a larger issue with using Flux for machine learning.

But I think we resolved the issue here - thanks for the help! Please keep me in the loop / ping me if you want to chat about any of the above.
