### ISSUE TITLE
change load() and load_data() to be more descriptive

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#323]
These names can be confusing for users. Could this be load_metadata and get_data? Or something like that to make them more descriptive?

**Comment by blaiszik** [comment]
What if we moved the args for `load()` into the Foundry constructor instead? and had somethings like this.

```python
f = Foundry("{{DOI or name}}", other args...)
f.get_data()
```

`load()` could then become basically a private method and we'd simplify the naming AND the usage
