### ISSUE TITLE
Clean up remaining Xtract artifacts

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#330]
_As a Developer, we don't want dead code hanging out in our source. Delete any references to dead Xtract code_

Context: Xtract was a service built by a GLabs team member that was previously used for our HTTPS download functionality. Once the team member moved on, the service became deprecated. We still have some comments and deprecated code floating around in `foundry`

# Acceptance criteria
1. There is no more reference to Xtract or any dead code related to it in `foundry_

**Comment by blaiszik** [comment]
PR here: https://github.com/MLMI2-CSSI/foundry/pull/349
