### ISSUE TITLE
Fix auth warning when instantiating Foundry class

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#334]
_As a Foundry user, I don't want unknown vague errors coming from dependencies (ahem, DLHub) and also I want this particular error (below) resolved_

Currently, when you instantiate the `Foundry` class, you get the following warning message (it does not error out), presumably from the `dlhub_sdk`. This probably has something to do with Foundry's handling of auths, potentially the search client/authorizer (see Slack convo from MDF #accelerate-internal below). 

![Image](https://user-images.githubusercontent.com/18538526/233468766-c1c734b8-52f6-47a6-8968-eac264232139.png)

Ryan identified the assignment of the [search authorizer](https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/foundry.py#L122) as a potential place of error. Investigate and resolve this bug

# Assumptions
1. The warning (error?) appears with DLHub >=2.0.0, Foundry >= 0.5.1

# Acceptance Criteria
1. Given a User instantiates the Foundry class, there is no warning or error output
2. (Optional) When there is this particular warning or error, a full stack trace is given so the user knows where it came from

## Additional info

> Aristana Scourtas
> here’s the current auth-handling code in  foundry https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/foundry.py#L70
> 
> [foundry.py](https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/foundry.py)
>             services = [
> <https://github.com/[MLMI2-CSSI/foundry](https://github.com/MLMI2-CSSI/foundry)|MLMI2-CSSI/foundry>MLMI2-CSSI/foundry | Added by [GitHub](https://chimad.slack.com/services/B04KJA60U8G)
> 7 replies
> 
> 
> ryan
>   [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935383129709?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
> Should this just be "search"? https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/foundry.py#L122 It might be worth printing out what auths is to see.
> [foundry.py](https://github.com/MLMI2-CSSI/foundry/blob/main/foundry/foundry.py)
>             search_authorizer=auths["search_authorizer"],
> <https://github.com/[MLMI2-CSSI/foundry](https://github.com/MLMI2-CSSI/foundry)|MLMI2-CSSI/foundry>MLMI2-CSSI/foundry | Added by [GitHub](https://chimad.slack.com/services/B04KJA60U8G)
> 
> 
> Aristana Scourtas
>   [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935442640739?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
> hmm I remember 
> [@blaiszik](https://chimad.slack.com/team/U04C6CMDF)
>  changed that a while back, but I can’t remember why
> 
> 
> ryan
>   [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935459913219?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
> I guess it'd fail there if that was wrong. There has been some work in funcx to remove the search authorizer requirement, but i don't think that'd change anything here.
> :+1:
> 1

Aristana Scourtas
  [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935509101359?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
I will poke around search, thanks ryan! I’m surprised the warning singled out dlhub specifically though?

ryan
  [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935567435509?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
i think the dlhub sdk checks if any of the authorizers are None and then raises that message.

Aristana Scourtas
  [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681935997497039?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
AH

Aristana Scourtas
  [23 hours ago](https://chimad.slack.com/archives/C04Q09L0H9D/p1681936023905139?thread_ts=1681935254.481069&cid=C04Q09L0H9D)
very helpful, thanks Ryan! :rainbow:

**Comment by ascourtas** [comment]
This issue is important to resolve so foundry appears usable, reliable, and understandable to users

**Comment by blaiszik** [comment]
This should be resolved with the removal of DLHub
