### ISSUE TITLE
Standardize docstrings

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#339]
_Some of the docstrings in the Foundry package are inconsistent, or mix style types. As a User, I want to be able to read clear documentation (both in the source code, and in the docs) that's consistent, readable, and clear._

# Assumptions:
1. We decide which docstring standard to use in Foundry

# Acceptance Criteria
1. All docstrings adhere to the same style/standard
2. All public functions have docstrings 
3. Docstrings are parsable and readable using documentation library (eg Sphinx, Gitbook, whatever it is we're using)

**Comment by kjschmidt913** [comment]
Ari did this!
