### ISSUE TITLE
Address inconsistencies with type hints

### ISSUE THREAD

**Issue by blue442** [MLMI2-CSSI/foundry#345]
Type hinting for function arguments are used in [some places](https://github.com/MLMI2-CSSI/foundry/blob/317d8c1b67eaf927a5718e55adc5d5eb2397b724/foundry/foundry.py#L499) but [not others](https://github.com/MLMI2-CSSI/foundry/blob/317d8c1b67eaf927a5718e55adc5d5eb2397b724/foundry/foundry.py#L625). It'd be nice if the implementation was consistent throughout the project one way or the other.

**Comment by kjschmidt913** [comment]
I think @ascourtas may have done this as a part of the JOSS work

**Comment by kjschmidt913** [comment]
Ari did this!
