### ISSUE TITLE
Design One Search Page

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#348]
One Search would be built using the [ALCF current search page](https://acdc.alcf.anl.gov/mdf/?q=*&filter-match-any.mdf.resource_type=dataset) ([repo here](https://github.com/globusonline/django-alcf-data-portal))--redesign it. There are filters already in place. Use what you think are useful in your design.

We would like one search page that can be filtered by MDF, Foundry, or Garden. 

Example usage: User should be able to click on "search MDF datasets" on the MDF website, and be brought to the One Search portal with the MDF filters already applied.

**Comment by ascourtas** [comment]
dupe

**Comment by kjschmidt913** [comment]
split out into more tasks:

- design search and tags
- design dataset cards
