### ISSUE TITLE
Implement new search page design

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#350]
Implement the new search page design for the [ALCF search page](https://acdc.alcf.anl.gov/mdf/?q=*&filter-match-any.mdf.resource_type=dataset) ([repo here](https://github.com/globusonline/django-alcf-data-portal)). 

This is one search page that can be filtered by MDF, Foundry, or Garden. 

Example usage: User should be able to click on "search MDF datasets" on the MDF website, and be brought to the One Search portal with the MDF filters already applied.

**Comment by ascourtas** [comment]
dupe
