### ISSUE TITLE
Design Noah's dataset views for the new dataset search portal

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#354]
Noah has a project in mind to bring in better data visualization and features in materials dataset viewing. This should be a part of the larger dataset portal redesign.

```[tasklist]
### Tasks
- [ ] Talk to Noah about what vision he has, what he wants displayed for a dataset. Take notes and link them here
- [ ] create a design on figma, miro, or whatever medium you are comfortable with
```

# Assumptions:
1. The designs in #351 have already been created
2. Implementation is a separate issue

# Acceptance Criteria
1. Given you show the designs to Noah, he is pleased and feels that it meets his needs
2. Notes from meeting with Noah and designs are linked here
3. (add other acceptance criteria after discussing with Noah)

**Comment by kjschmidt913** [comment]
Moved to MDF front end repo
