### ISSUE TITLE
Implement data preview for Foundry and MDF

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#359]
_As a User, I want to be able to preview the data in a dataset before I start using it_

Think like the Kaggle previews. 

For images, this could be a scaled-down version of a few of the images.
For tabular data, this could be a portion of the CSV rendered in the browser. 

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
Start with MDF dataset view (you can get to this on the [MDF website](https://materialsdatafacility.org/).

Here is a dataset page for reference: https://acdc.alcf.anl.gov/mdf/detail/akeel_soft_liners_v1.1/

You'll need to be added to this repo: https://github.com/globusonline/django-alcf-data-portal

**Comment by kjschmidt913** [comment]
Mark, could you make a PR for the Foundry-ML one you did once it's finished?

**Comment by kjschmidt913** [comment]
Mark made progress on this, but I don't know where the code is :(

**Comment by kjschmidt913** [comment]
Whoever picks this up, you are starting from scratch

**Comment by kjschmidt913** [comment]
moving to MDF and foundry website repos
