### ISSUE TITLE
Design usage of tags and search 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#364]
_As a User (Consumer, Publisher, Research Center, or Journal), I want to easily use tags to find things_

We want to have a clearer idea of how we want tags to work and what the user needs are here! Requires some fleshing out. Consult MDF, Foundry, and Garden User Personas

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
Phillip is asking the team for guidance on what would be helpful to change about this part of the page

**Comment by kjschmidt913** [comment]
This is implemented on the MDF search page that Chase is working on
