### ISSUE TITLE
Focused design of Garden <> Foundry <> MDF integrations

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#371]
_Design (from both a product and technical perspective) how models and datasets work across Garden <> Foundry <> MDF _

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
We figured out Foundry models using the Garden infrastructure

**Comment by kjschmidt913** [comment]
For right now, data integration means: Foundry remains in its own SDK and users can install and import it as needed for Garden

**Comment by ascourtas** [comment]
Need to come back to larger data discussions in the future
