### ISSUE TITLE
Break `load()` out of Foundry class `__init__` to improve workflow

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#379]
_As a User, I want to be able to know what a foundry function does without reading docs. I want a clear and intuitive workflow for using datasets_

There was some miscommunication in #323 (PR #358 ) about how best to disambiguate `load()` from `load_data()`. The solution developed entails privatizing `load()` by loading upon instantiation of the `Foundry` class, but this disrupts user workflows for loading multiple datasets, using `list()` or `search()`, etc. 

The new solution is to break `load()` out of `__init__`, but instead disambiguate by renaming and potentially further breaking up the functions. For example, one proposed solution is:
- `load()` --> `download_dataset()` and `view_metadata()`, OR `view_dataset()` where `download` is an optional boolean parameter
- `load_data()` --> `create_dataframe()`

Or renaming/refactoring solutions are possible, and require reading through the existing `load()` and `load_data()` implementations to decide on next steps

# Assumptions:
1. You are familiar with the contents of `load()` and `load_data()` and understand what they currently do
2. The implementation in #358 is currently in the `main` branch and needs to change per this ticket
3. We cannot cut a release unless we either change that or do some git wrangling
4. You have looked over the [Example Workflows](https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764558322356672&cot=14) defined in our Miro brainstorm

# Acceptance Criteria
1. Given I am a new user of Foundry, I can easily look at the list of functions in my IDE and know exactly what to do to download a dataset, preview the metadata, and use it in a dataframe format
2. As a User, I can accomplish any of the [User Workflows](https://miro.com/app/board/uXjVPrIdUhE=/?moveToWidget=3458764558322356672&cot=14) defined without running into friction based on the way downloading, loading, and previewing datasets is defined

```[tasklist]
### Tasks
- [x ] Review User Workflows (linked above) and discuss user needs and next steps with team
- [ ] Decide on naming solution for `load()` vs `load_data()` and any necessary refactor (see suggested example above)
- [ ] Implement changes 
```

**Comment by kjschmidt913** [comment]
+ update documentation + example notebooks to reflect new syntax

**Comment by kjschmidt913** [comment]
Is this sort of getting the boot since we are rethinking class structures?

**Comment by ascourtas** [comment]
Blocked on class restructure #395
