### ISSUE TITLE
JOSS paper edits from feedback

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry#380]
- [x] Review feedback from JOSS in PR
- [x] fix up `main` such that it is in a workable, deployable state (currently in PR #406 )
- [x] deploy existing changes in a minor/patch release
- [x] address JOSS issues opened in link below

**Comment by kjschmidt913** [comment]
issues: https://github.com/openjournals/joss-reviews/issues/5467

**Comment by ascourtas** [comment]
I'm going to take ownership of this one for Sprint 19

**Comment by ascourtas** [comment]
Main is fixed up, just need to run tests and make sure everything passes

**Comment by ascourtas** [comment]
complete! huzzah! We'll see if they have more to say, but I'll close this and open another issue if there are more iterations of edits
