### ISSUE TITLE
Make gameplan for potential overhaul of Foundry docs 

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#381]
_As a User, I want intuitive, comprehensive documentation. Sometimes it can be hard to find things in the foundry docs, or info is repeated across portions_

Look at other packages with really clean docs (Typer) and make a proposal of changes to the foundry docs to make them more navigable and intuitive. Some questions to ask are: do we want to move away from GitBook to something else? How do we want the docs to be structured? is information repeated? are the example code snippets easy to follow?

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
documentation is getting a huge overhaul with refactor
