### ISSUE TITLE
investigate GHA test failures

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#385]
Need to resolve. Perhaps need to fix our globus sdk package bounds? https://github.com/MLMI2-CSSI/foundry/actions/runs/5479160610/jobs/9980623198?pr=384 

Also previously there was an error in tests with auth and search -- worth investigating if it comes up

**Comment by blaiszik** [comment]
I wrote this in Slack, but these tests also fail locally with older versions of the Globus SDK. So there is likely something else that we changed that is breaking the tests. We should look at any changes to the test files since last successful run perhaps.

**Comment by ascourtas** [comment]
TODO: check if this is still an issue at all, may have been resolved

**Comment by ascourtas** [comment]
i believe this has been resolved; closing until further notice
