### ISSUE TITLE
Make related DOIs more visible in foundry UI

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#396]
_As a User, I want to know what datasets are related to the one I'm looking at_

Logan brought up the utility of related DOI visibility in Slack today -- for example, for the HydroNet dataset, to republish it it would be desirable to link to the original work of PNNL

As a user, it would be good to see the related DOIs of datasets more prominently in the web UI

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
moving to foundry website repo
