### ISSUE TITLE
Publish a dataset [WIP]

### ISSUE THREAD

**Issue by BenGalewsky** [MLMI2-CSSI/foundry#403]
_As a foundry publisher I want to publish my dataset so others can make use of my data_

Related to #404 , which should be completed first. 

After #404 is complete and the publishing flow is nailed down, finish the workflow by making the `publish()` method outlined in #404 actually publish the dataset to MDF, using the previously defined `FoundrySchema` and `FoundryDatacite` Pydantic documentation. Include tests and documentation.

# Description

# Acceptance Criteria
```python
f = Foundry()
ds = Dataset(title="my title")
ds.add_file(split_label="foo")

f.publish(ds)
```

**Comment by kjschmidt913** [comment]
This will be Steve's upcoming PR
