### ISSUE TITLE
Update Foundry example notebooks Globus download flags

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#425]

**Comment by blaiszik** [comment]
Each notebook has logic as below

```python
try:
    import google.colab
    no_local_server = True
    no_browser = True
    globus = False
except: # when not in google colab
    no_local_server = False
    no_browser = False
    globus = True
```

This combines the logic for choosing the auth path with choosing the download path. I think we should set globus=False in both cases by default, and have a commented out globus=True path that explains what it does. e.g., as below

```python
try:
    import google.colab
    no_local_server = True
    no_browser = True
    globus = False
except: # when not in google colab
    no_local_server = False
    no_browser = False
    globus = False


# If you would like to use Globus to download the data, ensure you have an endpoint running, and uncomment the following line
# globus = True
```

**Comment by kjschmidt913** [comment]
Looking at the larger picture, should we default to `globus=False` if the user doesn't pass in a globus parameter when initializing? Would that simplify things?

**Comment by blaiszik** [comment]
`globus=False` is the default now.  That's actually what caused the breaking change. Since we pass `globus` variable to all the class inits  in the notebook, I think setting it here explicitly is a shorter path than updating everywhere.
