### ISSUE TITLE
investigate Croissant data format

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#426]
_As a Publisher, I want to be able to publish an ML-ready dataset with as little friction as possible. I want to feel like it's easy and not a burden._

Determine whether or not `croissant` would help users get their datasets into the Foundry shape faster

http://mlcommons.org/croissant

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment]
Discussed at 1/24/2024 foundry dev meeting
