### ISSUE TITLE
Create an All Contributors List

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#436]
@all-contributors bot please add @blaiszik for infrastructure, tests, and code, data
@all-contributors bot please add @kjschmidt913  for infrastructure, tests, and code, data
@all-contributors bot please add @ascourtas  for infrastructure, tests, and code, data

**Comment by blaiszik** [comment]
@all-contributors bot please add @blaiszik for infrastructure, tests, and code, data

**Comment by blaiszik** [comment]
@all-contributors please add @blaiszik for infrastructure, tests, and code, data

**Comment by blaiszik** [comment]
@all-contributors bot please add @kjschmidt913 for infrastructure, tests, and code, data
@all-contributors bot please add @ascourtas for infrastructure, tests, and code, data

**Comment by ascourtas** [comment]
Note that this can happen for any issue -- doesn't have to be this one!

**Comment by ascourtas** [comment]
https://github.com/all-contributors bot please add @blue442  for infrastructure, tests, and code
