### ISSUE TITLE
Add Screenshots to README

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#46]
Add some illustrative screenshots to the README of what Foundry in action looks like

**Comment by kjschmidt913** [comment]
Run the [example notebooks](https://github.com/MLMI2-CSSI/foundry/tree/main/examples) for action shots or for inspiration of what to put there

**Comment by blaiszik** [comment]
Add screenshots from the slides e.g., the atom position finder ones.

**Comment by blaiszik** [comment]
Slides here: https://drive.google.com/drive/folders/0Bz9P8tnaPRx-dWtPQVg3TXdodGc?resourcekey=0-2nIRevdIu3Ie5qAYfzbbuA&usp=sharing
