### ISSUE TITLE
Documentation for running a model

### ISSUE THREAD

**Issue by blaiszik** [MLMI2-CSSI/foundry#54]
Update 6/13/22: Blocked by #23

**Comment by kjschmidt913** [comment]
We need model documentation (on gitbook) that will help external users publish and run models

**Comment by ascourtas** [comment]
@BraedenCu my understanding is you picked this up, but we haven't finished adding the model-running functionality to Foundry yet -- where are you at in this? If you're not too far, I'd suggest a different issue for now 🙂

**Comment by kjschmidt913** [comment]
here in change requests: https://app.gitbook.com/o/-MW5XeB7GD8rLHu7Mw6m/s/-MW6A6E0L1zra4m3voL_-38885591/~/changes/pr4wahF0PTqZriiBAzHP/publishing/publishing-datasets
